services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    expose:
      - "50021"
    deploy:
      replicas: 5

  nginx:
    image: nginx:stable
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8090:80"
    depends_on:
      - voicevox
